// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    // Retrieve the API key from the loaded environment variables
    // The '!' is used to assert that the value is non-null, assuming .env is loaded correctly.
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:947251316245:web:06bf96d789f7239043b01c',
    messagingSenderId: '947251316245',
    projectId: 'eduxcel-5a44b',
    authDomain: 'eduxcel-5a44b.firebaseapp.com',
    storageBucket: 'eduxcel-5a44b.firebasestorage.app',
    measurementId: 'G-TE1YXKQNHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQlWNYlz0M24KsduAk6S0Hww2J1tniJ8',
    appId: '1:947251316245:android:c3c440d1475ba49643b01c',
    messagingSenderId: '947251316245',
    projectId: 'eduxcel-5a44b',
    storageBucket: 'eduxcel-5a44b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqN3dJeiRvkyxiYgIBSLlScJ5x89QfY6M',
    appId: '1:947251316245:ios:3ff4f6916d63a2d543b01c',
    messagingSenderId: '947251316245',
    projectId: 'eduxcel-5a44b',
    storageBucket: 'eduxcel-5a44b.firebasestorage.app',
    androidClientId:
        '947251316245-gkujo048k15i93hc7g4rd0sstgrhb33n.apps.googleusercontent.com',
    iosClientId:
        '947251316245-qqgc7j890b3rup4v2dlented3pjq9tst.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduxcel',
  );
}
