import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'home_page.dart'; // Custom home page widget
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'screens/profile_screen.dart'; // 👈 Added from main branch

void main() async {
  // Ensure that Flutter widgets are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise .env
